;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        electric-pair-delete-pair
        evil-backward-char
        evil-backward-word-begin
        evil-change
        evil-delete
        evil-insert
        evil-normal-state
        evil-open-above
        evil-open-below
        evil-previous-line
        ))

(setq mc/cmds-to-run-once
      '(
        evil-delete-backward-char-and-join
        evil-forward-char
        evil-insert-line
        evil-next-line
        ))
