(setq js3-auto-indent-p t)
(setq js3-curly-indent-offset 0)
(setq js3-enter-indents-newline t)
(setq js3-expr-indent-offset 2)
(setq js3-indent-on-enter-key t)
(setq js3-lazy-commas t)
(setq js3-lazy-dots t)
(setq js3-lazy-operators t)
(setq js3-paren-indent-offset 2)
(setq js3-square-indent-offset 4)
(setq js3-consistent-level-indent-inner-bracket t)
(provide 'js3-mode-settings)
